language: python
python:
  - "3.5"
  - "3.6"

env:
  global:
    - HYDRA_LAUNCHER=fork
    - OMPI_MCA_rmaps_base_oversubscribe=yes
    - MPI=mpich

before_install:
    - sudo apt-get update -q
    - python$PY -m pip install Cython
    - python$PY -m pip install numpy
    - bash parsl/executors/extreme_scale/install-mpi.sh $MPI
    - python$PY --version
    - python$PY -m cython --version
    - python$PY -c "import numpy;print(numpy.__version__)"
    - if [[ "$MPI" == "mpich"   ]]; then mpichversion; fi
    - if [[ "$MPI" == "openmpi" ]]; then ompi_info;    fi

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install flake8
    - python setup.py install

# Os tests
os:
    - linux

# command to run tests
script:
    - export PARSL_TESTING="true"
    - pip install -r test-requirements.txt
    - flake8 parsl/

      # do this before any testing, but not in-between tests
    - rm -f .coverage

    - (for test in parsl/tests/test*/test*; do pytest $test --config local --cov=parsl --cov-append --cov-report= ; export X=$? ; echo X is $X ; if [[ "$X" != 0 ]] && [[ "$X" != 5 ]]; then exit 1; fi; done ) ;
      # allow exit code 5; this means pytest did not run a test in the
      # specified file

    - coverage report
      # prints report of coverage data stored in .coverage

    # - pytest parsl/tests --config parsl/tests/configs/local_threads.py
    # - pytest parsl/tests --config parsl/tests/configs/local_ipp.py
